### ISSUE TITLE
Update to injury doesn't persist

### ISSUE THREAD

**Issue by djohnson** [daisybill/daisybill_api#51]
I'm attempting to update an Injury, but while the object returns true the change does not persist on the remote side.  

```ruby
injury = DaisybillApi::Models::Injury.find(155774)
=> <DaisybillApi::Models::Injury patient_id: 154977, id: 155774, ...>>

injury.end_date
=> Mon, 22 Nov 2010

injury.end_date = Date.new(2010,11,21)
=> Sun, 21 Nov 2010

injury.end_date
=> Sun, 21 Nov 2010

injury.save
=> true

injury.end_date
=> Mon, 22 Nov 2010

injury = DaisybillApi::Models::Injury.find(155774)
=> <DaisybillApi::Models::Injury patient_id: 154977, id: 155774, ...>>

injury.end_date
=> Mon, 22 Nov 2010
```

**Comment by mntj** [comment]
Hi @djohnson 

Thanks for reporting this. I'll look into it and will be in touch when I have more info.

**Comment by mntj** [comment]
@djohnson Just duplicated the issue - I'll let you know when a fix is deployed.

**Comment by mntj** [comment]
@djohnson We deployed a fix this morning, let me know if you have any further issues. Thanks!
