### ISSUE TITLE
Unable to assign Payer for Injuries

### ISSUE THREAD

**Issue by djohnson** [daisybill/daisybill_api#54]
Given a Claims Administrator that has multiple Payers it should be possible to assign the Payer ID on Injury create/update.  Also the Injury model should support looking up which Payer is associated.

**Comment by mntj** [comment]
@djohnson Hi Darren, thanks for bringing this up. This behavior will be added soon, I'll be in touch when it's ready.

**Comment by mntj** [comment]
@djohnson Added support for assigning payers to injuries
