### ISSUE TITLE
Models should set appropriate errors and return false if not saved

### ISSUE THREAD

**Issue by djohnson** [daisybill/daisybill_api#58]
When attempting to create a `DaisybillApi::Models::Bill` with a service line item that has a units value over 9999 the object is returned but is not saved.  The returned object does not have an ID set, `.valid?` returns true, and `.errors` is empty.  I believe the call to create should have returned false, `valid?` would return `false`, and `errors` would have something to the effect that service line item quantity exceeds some maximum.  As it stands there doesn't appear to be a way to handle  the case where a Daisy object doesn't actually save unless you inspect the object for an ID or some other work around, but even then I don't see anyway to know what the problem is.  I'm not sure if this impacts any other models, but I would think they should all handle api errors and translate them to the ruby objects appropriately.

**Comment by coreyleveen** [comment]
@djohnson Hi Darren, thanks for bringing this to our attention. I'll look into it and get back to you with any updates

**Comment by coreyleveen** [comment]
@djohnson I've tried to replicate the issue, and while the unsaved bill object is returned instead of returning `false` (which should not happen), I'm able to view the errors associated with the issue, and `valid?` returns false for me. 

Here's what I tried:

```ruby
sli = DaisybillApi::Models::ServiceLineItem.new(
  procedure_code:   "99214",
  units:            10_000,
  diagnosis_code_1: "7400"
)

bill = DaisybillApi::Models::Bill.create(
  injury_id:          761,
  date_of_service:    "2016-02-15",
  place_of_service:   3016,
  diagnosis_codes:    ["12345"],
  diagnosis_type:     "Icd9",
  service_line_items: [sli]
) # => <DaisybillApi::Models::Bill injury_id: 761, id: nil...>

bill.errors.messages # => {:"service_line_items.units"=>["is not an acceptable number (1..9999)"]}
bill.valid?          # => false
```

Would you mind providing the code you used to produce this issue, as well as the version of the gem you're using?

**Comment by djohnson** [comment]
Thanks for looking into this!  My test was on the latest master with the staging api endpoint.  

I just retested my previously failing case and it now appears to be working as expected, bill.save returns false, valid returns false, and the error message is there as well.  I don't know why it was failing before but as i'm unable to reproduce i'm marking this closed.
