### ISSUE TITLE
Pagination Per Page should be configurable 

### ISSUE THREAD

**Issue by djohnson** [daisybill/daisybill_api#61]
Each index action should be able to pull up to the api's maximum allowed per_page and this should be documented somewhere.  Currently you have to probe each endpoint with a high per page to see what the limit is going to be, some are 25 some are 100, as it does not seem to be documented anywhere.  Is it possible to increase the max per page to a standardized 100 for all endpoints?

**Comment by coreyleveen** [comment]
@djohnson Hi there. I apologize for the slow response. 

Our documentation has been updated to include a section on pagination [here](http://dev.daisybill.com/docs/getting-started). Currently the only endpoints that support a maximum `per_page` value of 100 are the index endpoints for claims administrators and payers, with the rest supporting a maximum value of 25. We don't currently have plans to increase the limit for other endpoints, but we can notify you when that changes if you'd like.

I'm going to close this but if you have any questions feel free to open another.
